language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

script:
  - ./bin/phpunit -c ./phpunit.xml --coverage-text
